name: Weekly Benchmark

on:
  schedule:
    - cron: '0 0 * * 0'  # Каждое воскресенье в 00:00 UTC
  workflow_dispatch:      # Позволяет запускать вручную

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r report/requirements.txt

      - name: Run benchmark tests
        run: python3 report/run_tests.py

      - name: Generate report and update chart
        run: python3 report/generate_report.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md report/performance_over_limits_chart.png
          # Проверяем, есть ли изменения для коммита
          if ! git diff --staged --quiet; then
            git commit -m "Weekly benchmark: Update performance chart and README"
            git push
          else
            echo "No changes to commit."
          fi
